sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t thenatureofsoftware/jdk-arm64 .
# test image
- docker run thenatureofsoftware/jdk-arm64 java --version
# push image
