sudo: required
services:
- docker
language: bash
script:
# prepare qemu
- docker run --rm --privileged multiarch/qemu-user-static:register --reset
# build image
- docker build -t thenatureofsoftware/jdk-arm64 .
# test image
- docker run thenatureofsoftware/jdk-arm64 java -version
# push image
- >
  if [ "$TRAVIS_BRANCH" == "master" ] || [ "$TRAVIS_BRANCH" == "jdk9" ] && [ "$TRAVIS_PULL_REQUEST" == "false" ]; then
    docker login -u="$DOCKER_USER" -p="$DOCKER_PASS"
    TAG=$(grep VERSION Dockerfile|awk 'NF>1{print $NF'})
    docker tag thenatureofsoftware/jdk-arm64 thenatureofsoftware/jdk-arm64:$TAG
    docker push thenatureofsoftware/jdk-arm64:$TAG
    docker push thenatureofsoftware/jdk-arm64:latest
  fi
